# Generated by Django 5.1.2 on 2024-12-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppV', '0002_entrada_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='cuerpo',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='subtitulo',
            field=models.CharField(max_length=1000),
        ),
    ]
